### ISSUE TITLE
Empty minified css

### ISSUE THREAD

**Issue by pascalgermain** [znck/vue-keynote#6]
Hi,

As @Julien76 said, thanks for this great library :)

The docs say to use css from here, but there's no minified css: [//unpkg.com/vue-keynote/dist/vue-keynote.min.css](//unpkg.com/vue-keynote/dist/vue-keynote.min.css)

Trying to fork and build locally gives me no file at all.

Thanks!

**Comment by znck** [comment]
Fixed in https://github.com/znck/vue-keynote/releases/tag/v0.1.6
